# Generated by Django 4.2.6 on 2024-05-16 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_co_nm', models.CharField(max_length=20)),
                ('fin_co_no', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PensionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('pnsn_kind', models.CharField(max_length=10)),
                ('pnsn_kind_nm', models.TextField()),
                ('prdt_type', models.CharField(max_length=10)),
                ('prdt_type_nm', models.TextField()),
                ('dcls_rate', models.FloatField()),
                ('guar_rate', models.FloatField()),
                ('etc', models.TextField()),
                ('fin_co_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_product.financialcompany')),
            ],
        ),
        migrations.CreateModel(
            name='PensionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=10)),
                ('intr_rate_type_nm', models.TextField()),
                ('rsrv_type', models.CharField(max_length=10)),
                ('rsrv_type_nm', models.TextField()),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('fin_co_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_product.financialcompany')),
                ('fin_prdt_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_product.pensionproduct')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentSavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('join_member', models.TextField()),
                ('max_limit', models.IntegerField()),
                ('etc_note', models.TextField()),
                ('fin_co_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_product.financialcompany')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentSavingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=10)),
                ('intr_rate_type_nm', models.TextField()),
                ('rsrv_type', models.CharField(max_length=10)),
                ('rsrv_type_nm', models.TextField()),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('fin_co_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_product.financialcompany')),
                ('fin_prdt_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_product.installmentsavingproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('join_member', models.TextField()),
                ('max_limit', models.IntegerField()),
                ('etc_note', models.TextField()),
                ('fin_co_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_product.financialcompany')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=10)),
                ('intr_rate_type_nm', models.TextField()),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('fin_co_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_product.financialcompany')),
                ('fin_prdt_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_product.depositproduct')),
            ],
        ),
    ]
