# Generated by Django 4.2.6 on 2024-05-21 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cur_unit', models.CharField(max_length=10)),
                ('cur_nm', models.CharField(max_length=30)),
                ('ttb', models.FloatField()),
                ('tts', models.FloatField()),
                ('deal_bas_r', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_co_nm', models.CharField(max_length=50)),
                ('fin_co_no', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentSavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_cd', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('join_member', models.TextField()),
                ('max_limit', models.BigIntegerField(null=True)),
                ('etc_note', models.TextField()),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=20)),
                ('rate_1', models.FloatField(blank=True)),
                ('rate_3', models.FloatField(blank=True)),
                ('rate_6', models.FloatField(blank=True)),
                ('rate_12', models.FloatField(blank=True)),
                ('rate_24', models.FloatField(blank=True)),
                ('rate_36', models.FloatField(blank=True)),
                ('rate_1_p', models.FloatField(blank=True)),
                ('rate_3_p', models.FloatField(blank=True)),
                ('rate_6_p', models.FloatField(blank=True)),
                ('rate_12_p', models.FloatField(blank=True)),
                ('rate_24_p', models.FloatField(blank=True)),
                ('rate_36_p', models.FloatField(blank=True)),
                ('fin_co_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_product.financialcompany')),
                ('joined_user', models.ManyToManyField(blank=True, related_name='user_installment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentSavingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=10)),
                ('intr_rate_type_nm', models.TextField()),
                ('rsrv_type', models.CharField(max_length=10)),
                ('rsrv_type_nm', models.TextField()),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('dcls_month', models.CharField(max_length=10)),
                ('fin_co_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_product.financialcompany')),
                ('fin_prdt_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_product.installmentsavingproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_cd', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('join_member', models.TextField()),
                ('max_limit', models.BigIntegerField(null=True)),
                ('etc_note', models.TextField()),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=20)),
                ('rate_1', models.FloatField(blank=True)),
                ('rate_3', models.FloatField(blank=True)),
                ('rate_6', models.FloatField(blank=True)),
                ('rate_12', models.FloatField(blank=True)),
                ('rate_24', models.FloatField(blank=True)),
                ('rate_36', models.FloatField(blank=True)),
                ('rate_1_p', models.FloatField(blank=True)),
                ('rate_3_p', models.FloatField(blank=True)),
                ('rate_6_p', models.FloatField(blank=True)),
                ('rate_12_p', models.FloatField(blank=True)),
                ('rate_24_p', models.FloatField(blank=True)),
                ('rate_36_p', models.FloatField(blank=True)),
                ('fin_co_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_product.financialcompany')),
                ('joined_user', models.ManyToManyField(blank=True, related_name='user_deposit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=10)),
                ('intr_rate_type_nm', models.TextField()),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('dcls_month', models.CharField(max_length=10)),
                ('fin_co_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_product.financialcompany')),
                ('fin_prdt_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_product.depositproduct')),
            ],
        ),
    ]
