# Generated by Django 4.2.6 on 2024-05-21 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproduct',
            name='joined_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_deposit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='rate_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='rate_12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='rate_12_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='rate_1_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='rate_24',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='rate_24_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='rate_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='rate_36',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='rate_36_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='rate_3_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='rate_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='rate_6_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installmentsavingproduct',
            name='joined_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_installment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='installmentsavingproduct',
            name='rate_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installmentsavingproduct',
            name='rate_12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installmentsavingproduct',
            name='rate_12_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installmentsavingproduct',
            name='rate_1_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installmentsavingproduct',
            name='rate_24',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installmentsavingproduct',
            name='rate_24_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installmentsavingproduct',
            name='rate_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installmentsavingproduct',
            name='rate_36',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installmentsavingproduct',
            name='rate_36_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installmentsavingproduct',
            name='rate_3_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installmentsavingproduct',
            name='rate_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installmentsavingproduct',
            name='rate_6_p',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
