# Generated by Django 4.2.6 on 2024-05-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_product', '0004_exchangrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangrate',
            old_name='deal_base_r',
            new_name='deal_bas_r',
        ),
    ]
