# Generated by Django 4.2.6 on 2024-05-22 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_username_comment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='username',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
    ]
